In [3]:
import torch
torch.cuda.is_available()

False

In [10]:
x = torch.empty(2,2,3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [8]:
x = torch.rand(2,2,3)
print(x)

tensor([[[0.9781, 0.7829, 0.4837],
         [0.0914, 0.5602, 0.0916]],

        [[0.6876, 0.1182, 0.0275],
         [0.4409, 0.2531, 0.2956]]])


In [9]:
x = torch.zeros(2,2,3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [11]:
x = torch.ones(2,2,3)
print(x)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [13]:
x = torch.empty(2,2,3, dtype=int)
print(x)
print(x.size)

tensor([[[32088589733920882, 25896191785762913, 29273895802044496],
         [12948067979231343, 29555336417116214, 29555366481887330]],

        [[31525390671741044, 27303532308922465, 25896191785238631],
         [27866512327901300, 32651599815639144, 25896191785697385]]])
<built-in method size of Tensor object at 0x0000025A1F5ABB80>


In [14]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.6374, 0.0781],
        [0.6059, 0.8382]])
tensor([[0.3363, 0.1284],
        [0.2803, 0.0590]])


In [15]:
z = x + y # element-wise addition
print(z)

tensor([[0.9737, 0.2065],
        [0.8862, 0.8972]])


In [26]:
zb = torch.add(x,y) # element-wise addition
print(zb)

tensor([[2.8860, 0.4407],
        [2.7037, 3.4118]])


In [19]:
y.add_(x) # in-place addition

tensor([[2.2486, 0.3627],
        [2.0979, 2.5736]])

In [28]:
a = torch.rand(5,3)
print(a)

tensor([[0.7298, 0.3369, 0.8203],
        [0.4186, 0.3031, 0.2574],
        [0.9351, 0.0999, 0.2860],
        [0.7150, 0.9168, 0.7595],
        [0.3084, 0.6030, 0.7222]])


In [33]:
print(a[:,1]) # slicing all row and column 1
print(a[1,:]) # slicing row 1 and all column
print(a[1,1].item()) # slicing/get item from row 1 colomn 1.

tensor([0.3369, 0.3031, 0.0999, 0.9168, 0.6030])
tensor([0.4186, 0.3031, 0.2574])
0.3031314015388489


In [38]:
x = torch.rand(4,4)
print(x)
y = x.view(16) # resize tensor
print(y)

tensor([[0.7733, 0.7363, 0.3737, 0.1335],
        [0.0604, 0.6852, 0.4599, 0.6467],
        [0.8122, 0.8705, 0.1010, 0.0190],
        [0.8798, 0.0381, 0.5727, 0.7256]])
tensor([0.7733, 0.7363, 0.3737, 0.1335, 0.0604, 0.6852, 0.4599, 0.6467, 0.8122,
        0.8705, 0.1010, 0.0190, 0.8798, 0.0381, 0.5727, 0.7256])


In [39]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [42]:
c = torch.ones(3)
print(c)
d = c.numpy()
print(d)

c.add_(1) # inplace addition
print(c) # value changed
print(d) # value of d changed also -> pointing to same location of c

tensor([1., 1., 1.])
[1. 1. 1.]
tensor([2., 2., 2.])
[2. 2. 2.]


In [43]:
#operations on the GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device) # create torch on the device(GPU)
    y = torch.ones(5)
    y = y.to(device) # move y to GPU
    z = x - y # operation performed in the GPU
    #to conevert to numbpy first move to CPU
    z = z.to("cpu")