## Gradient Calculation with Autograd

In [1]:
import torch

In [3]:
x = torch.rand(3, requires_grad=True) #specify grad function and 
                                    # create cakobian matrix (chain rule)
print(x)

tensor([0.3636, 0.5524, 0.1028], requires_grad=True)


In [4]:
y = x + 2 # creating a node, y will have attribute grad_fn
print(y)

tensor([2.3636, 2.5524, 2.1028], grad_fn=<AddBackward0>)


In [5]:
z = y * 2
print(z)

tensor([4.7273, 5.1048, 4.2055], grad_fn=<MulBackward0>)


In [6]:
z = z.mean() # get mean and z becomes scalar
print(z)

tensor(4.6792, grad_fn=<MeanBackward0>)


In [7]:
z.backward() # dz/dx - calculate gradient z with respect to x
print(x.grad)

tensor([0.6667, 0.6667, 0.6667])


In [9]:
# if not scalar a vector is needed to be passed into backward fun
# because in the background is is a sacordian matrix
z2 = y * 2
v = torch.tensor([0.1,0.1,0.01], dtype=torch.float32)
z2.backward(v)
print(x.grad)

tensor([0.8667, 0.8667, 0.6867])


In [13]:
#how to prevent pytorch to track gradients
x = torch.rand(3, requires_grad=True)
print(x)
# 3 options
# First Option
x.requires_grad_(False)
print(x)

tensor([0.5750, 0.8646, 0.0301], requires_grad=True)
tensor([0.5750, 0.8646, 0.0301])


In [15]:
# Second Option
x2 = torch.rand(3, requires_grad=True)
print(x2)
y = x2.detach() # use detach
print(y)

tensor([0.0970, 0.9302, 0.5458], requires_grad=True)
tensor([0.0970, 0.9302, 0.5458])


In [16]:
# Third Option
x3 = torch.rand(3, requires_grad=True)
print(x3)
with torch.no_grad():
    y = x3 + 2
    print(y)

tensor([0.2811, 0.5240, 0.5349], requires_grad=True)
tensor([2.2811, 2.5240, 2.5349])


In [22]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_() # empty the gradient or we can use optimizers

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [24]:
weights = torch.ones(5, requires_grad=True)
optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor